# Generated by Django 3.2.25 on 2025-01-18 08:07

from django.db import migrations, models
import treasure_rewards.models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_rewards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardimage',
            name='pixel_art_path',
        ),
        migrations.AddField(
            model_name='rewardimage',
            name='pixel_art_image',
            field=models.ImageField(blank=True, null=True, upload_to=treasure_rewards.models.upload_to),
        ),
    ]
