# Generated by Django 3.2.25 on 2025-01-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_rewards', '0002_auto_20250118_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardimage',
            name='tmdb_id',
            field=models.CharField(default='none', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
