# Generated by Django 3.2.25 on 2025-01-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_rewards', '0004_rename_pixel_art_image_rewardimage_pixel_art_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardimage',
            name='movie_poster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
