# Generated by Django 3.2.25 on 2025-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_rewards', '0005_rewardimage_movie_poster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardimage',
            name='tmdb_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
