# Generated by Django 3.2.25 on 2025-01-27 22:28

from django.db import migrations, models
import movie_posters.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_posters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieposter',
            name='pixel_art_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=movie_posters.models.upload_to),
        ),
    ]
