# Generated by Django 3.2.25 on 2025-01-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_posters', '0002_movieposter_pixel_art_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieposter',
            name='pixel_art_image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
