# Generated by Django 3.2.25 on 2025-02-09 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_posters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('movie_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by_users', to='movie_posters.movieposter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
